BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `USER` (
	`USER_ID`	INTEGER,
	`USERNAME`	VARCHAR ( 20 ) NOT NULL,
	`PASSWORD`	VARCHAR ( 20 ) NOT NULL,
	`CREATED_DATE`	DATE NOT NULL,
	PRIMARY KEY(`USER_ID`)
);
CREATE TABLE IF NOT EXISTS `REVIEW_DEST_WISATA` (
	`REVIEW_ID`	INTEGER,
	`DEST_ID`	INTEGER NOT NULL,
	`TGL_REVIEW_BUAT`	DATE NOT NULL,
	PRIMARY KEY(`REVIEW_ID`),
	FOREIGN KEY(`DEST_ID`) REFERENCES `DEST_WISATA`(`DEST_ID`)
);
CREATE TABLE IF NOT EXISTS `PLAN_WISATA` (
	`PLAN_ID`	INTEGER,
	`DEST_ID`	INTEGER NOT NULL,
	`USER_ID`	INTEGER NOT NULL,
	`TGL_KUNJUNGAN`	DATE NOT NULL,
	`TGL_RENCANA_BUAT`	DATE NOT NULL,
	FOREIGN KEY(`USER_ID`) REFERENCES `USER`(`USER_ID`),
	FOREIGN KEY(`DEST_ID`) REFERENCES `DEST_WISATA`(`DEST_ID`),
	PRIMARY KEY(`PLAN_ID`)
);
CREATE TABLE IF NOT EXISTS `KATEGORI` (
	`KATEGORI_ID`	INTEGER,
	`NAMA_KATEGORI`	VARCHAR ( 20 ) NOT NULL,
	`DESKRIPSI_KATEGORI`	TEXT,
	`TGL_KAT_BUAT`	DATE NOT NULL,
	PRIMARY KEY(`KATEGORI_ID`)
);
INSERT INTO `KATEGORI` VALUES (1,'Wisata Mendaki','Wisata Mendaki','2019-05-10');
INSERT INTO `KATEGORI` VALUES (2,'Wisata Curug','Wisata Curug','2019-05-10');
INSERT INTO `KATEGORI` VALUES (3,'Wisata Pantai','Wisata Pantai','2019-05-10');
INSERT INTO `KATEGORI` VALUES (4,'Wisata Keluarga','Wisata Keluarga','2019-05-10');
INSERT INTO `KATEGORI` VALUES (5,'Wisata Religi','Wisata Religi','2019-05-10');
CREATE TABLE IF NOT EXISTS `DEST_WISATA` (
	`DEST_ID`	INTEGER,
	`KATEGORI_ID`	INTEGER NOT NULL,
	`NAMA_DEST`	VARCHAR ( 20 ) NOT NULL,
	`DESKRIPSI_DEST`	TEXT,
	`LATITUDE`	REAL NOT NULL,
	`LONGITUDE`	REAL NOT NULL,
	`TGL_DEST_BUAT`	DATE NOT NULL,
	FOREIGN KEY(`KATEGORI_ID`) REFERENCES `KATEGORI`(`KATEGORI_ID`),
	PRIMARY KEY(`DEST_ID`)
);
INSERT INTO `DEST_WISATA` VALUES (1,2,'Curug Cilengkrang','',-6.8958662,107.7251764,'2019-05-10');
COMMIT;
